language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache:
  apt: true
  cargo: true
  directories:
    - $HOME/.cache/Tectonic
before_install:
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends \
      ca-certificates \
      curl \
      libfontconfig1-dev \
      libgraphite2-dev \
      libharfbuzz-dev \
      libicu-dev \
      libssl-dev \
      zlib1g-dev
install:
  - cargo install tectonic
script:
  - tectonic sample-handout.tex
after-script:
  - ls -lah *.pdf
