language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache:
  - apt
  - cargo
  directories:
    - $HOME/.cache/Tectonic
before_install:
  - sudo apt-get install -y curl
install:
  - cargo install tectonic
script:
  - tectonic sample-handout.tex
after-script:
  - ls -lah *.pdf
